### ISSUE TITLE
Answer is not displayed.

### ISSUE THREAD

**Issue by ericwgreene** [zaaraa-z/fun-projects#1]
Here is a video link demonstrating my experience with the Memory Cards application.

https://youtu.be/u_vJNjUT70w

You will see I can create cards and navigate between them, but when I try to view the answer it briefly displays and then disappears.

The application is really nice. Fix this and store the cards to a database and allow users to create an account and save their cards and you will have a real app people will use.

**Comment by zaaraa-z** [comment]
Thanks.
It seems that it is a browser compatibility issue. It is working in Chrome and Firefox. 
I will solve the issue in Safari soon.

**Comment by zaaraa-z** [comment]
Safari compatibility is fixed.
Please check it out and let me know if it is approved.
commit: b4c6270
@ericwgreene

**Comment by zaaraa-z** [comment]
The issue is fixed. 
Now it is working well in safari.
